### ISSUE TITLE
Bug: Github Action fails

### ISSUE THREAD

**Issue by jaiakash** [jaiakash/its_urgent#15]
![image](https://user-images.githubusercontent.com/33419526/180370485-ba4d160d-305a-42f7-b29c-513d6cc55646.png)

Github Action fails at `flutter analyze .`

**Comment by nitin-787** [comment]
### Bhaiya ye github actions kya hota hai? code test automate krne ke liye use hota hai ke, devops ke under aata hai kya?

**Comment by nitin-787** [comment]
### ye close kr do na @jaiakash

**Comment by jaiakash** [comment]
Fixed #18
